import {loadState,saveState,migrateState} from './storage.js';
import {upsertInventoryItem,setInventoryStatus} from './inventory.js';
import {addHouseholdNote,resolveHouseholdNote,addTopUpRequest,helperVisibleState,resolveTopUpByName} from './helper.js';
import {recordMealRating,buildFeedbackContext} from './feedback.js';
import {buildShoppingList,setShoppingRoute,setShoppingChecked} from './shopping.js';
import {buildWeeklyPrompt,buildSwapPrompt,buildPartyPrompt} from './prompts.js';
import {validateWeeklyPlan,applySwap,callAnthropic} from './planner.js';
import {cloudEnabled,createSupabase,signIn,signOut,loadProfile,loadHouseholdState,saveHouseholdState,mergeCloudState} from './cloud.js';

let state=loadState(localStorage), cloudClient=null, cloudProfile=null;
const cfg=window.KITCHEN_CLOUD_CONFIG||{}, $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const clone=x=>structuredClone(x);
const latest=status=>[...(state.weeklyPlans||[])].filter(p=>!status||p.status===status).sort((a,b)=>String(a.weekStart).localeCompare(String(b.weekStart))).at(-1)||null;
const approved=()=>latest('approved');
const draft=()=>[...(state.weeklyPlans||[])].reverse().find(p=>p.status==='draft')||null;
const allIngredients=p=>(p?.days||[]).flatMap(d=>['lunch','dinner'].flatMap(k=>d[k]?.keyIngredients||[]));
const nextMonday=()=>{const d=new Date(),add=(8-d.getDay())%7||7;d.setDate(d.getDate()+add);return d.toISOString().slice(0,10)};
function note(msg,bad=false){const n=$('notice');n.textContent=msg;n.classList.toggle('error',bad);n.classList.remove('hidden');setTimeout(()=>n.classList.add('hidden'),4000)}
function persist(next=state){state=next;saveState(localStorage,state);render();if(cloudClient&&cloudProfile?.household_id)saveHouseholdState(cloudClient,cloudProfile.household_id,state).catch(e=>note(`Cloud sync failed: ${e.message}`,true));}
function mode(m){if(cloudProfile?.role)m=cloudProfile.role==='helper'?'helper':'parent';state.ui.mode=m;$('parentApp').classList.toggle('hidden',m!=='parent');$('helperApp').classList.toggle('hidden',m!=='helper');$('parentModeBtn').classList.toggle('active',m==='parent');$('helperModeBtn').classList.toggle('active',m==='helper');if(m==='helper')renderHelper();}
function tab(name){state.ui.activeTab=name;document.querySelectorAll('#parentTabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('hidden',x.id!==`tab-${name}`));}
function recipe(d){return d?.recipeSource?.searchQuery?`https://www.google.com/search?q=${encodeURIComponent(d.recipeSource.searchQuery)}`:''}
function meal(day,slot,d,isDraft){if(!d)return `<div class="meal"><small>${slot}</small>—</div>`;return `<div class="meal"><small>${slot}</small><div class="meal-name">${esc(d.name)}</div><div class="meal-desc">${esc(d.description||'')}</div><div class="tags"><span class="tag">${esc(d.cuisine||'')}</span><span class="tag">${esc(d.exposureLevel||'')}</span></div>${d.prepNotes?`<div class="meal-desc"><b>Prep:</b> ${esc(d.prepNotes)}</div>`:''}${recipe(d)?`<a class="recipe" href="${recipe(d)}" target="_blank">Recipe ↗</a>`:''}${isDraft?`<div class="meal-actions"><button data-swap-day="${esc(day)}" data-swap-slot="${slot}">Swap meal</button></div>`:''}</div>`}
function renderPlan(){const p=draft()||approved(),isDraft=Boolean(draft());$('approveBtn').classList.toggle('hidden',!isDraft);$('planStatus').classList.toggle('hidden',!p);if(p)$('planStatus').textContent=isDraft?'Draft week — review, swap, then approve.':`Approved week ${p.weekStart}.`;if(!p){$('weeklyPlan').className='meal-grid empty-state';$('weeklyPlan').textContent='Generate a draft to see next week\'s meals.';return}$('weeklyPlan').className='meal-grid';$('weeklyPlan').innerHTML=p.days.map(d=>`<article class="day-card"><div class="day-head">${esc(d.day)}</div>${meal(d.day,'lunch',d.lunch,isDraft)}${meal(d.day,'dinner',d.dinner,isDraft)}</article>`).join('')}
function renderInventory(){const group=dom=>state.inventory.filter(x=>x.domain===dom).map(i=>`<div class="inventory-row"><div><b>${esc(i.name)}</b><div class="shop-source">${i.quantity??''} · updated by ${esc(i.updatedBy||'')}</div></div><div class="status-buttons">${['plenty','low','out'].map(s=>`<button data-inv-id="${esc(i.id)}" data-status="${s}" class="${i.status===s?'active':''}">${s}</button>`).join('')}</div></div>`).join('')||'<p class="hint">No items yet.</p>';$('inventoryLists').innerHTML=`<section class="inventory-domain"><h2>Food inventory</h2>${group('food')}</section><section class="inventory-domain"><h2>Household supplies</h2>${group('household')}</section>`;$('parentInbox').innerHTML=state.householdNotes.filter(n=>!n.resolved).map(n=>`<div class="inbox-row"><div>${esc(n.text)}</div><button class="tiny" data-resolve-note="${esc(n.id)}">Resolve</button></div>`).join('')||'<p class="hint">No open notes.</p>'}
function renderShopping(){const items=state.shoppingItems||[];$('shoppingList').innerHTML=items.map(i=>`<div class="shopping-row ${i.checked?'checked':''}"><input type="checkbox" data-shop-check="${esc(i.id)}" ${i.checked?'checked':''}><div><b>${esc(i.name)}</b><div class="shop-source">${esc(i.source||'')}</div></div><select data-shop-route="${esc(i.id)}"><option value="helper_buys" ${i.route==='helper_buys'?'selected':''}>Helper buys</option><option value="online_delivery" ${i.route==='online_delivery'?'selected':''}>Online delivery</option><option value="already_have" ${i.route==='already_have'?'selected':''}>Already have</option></select></div>`).join('')||'<p class="hint">Approve a week or add top-ups first.</p>'}
function renderFamily(){const ms=state.familyMembers.filter(m=>m.role!=='helper');$('familyProfiles').innerHTML=ms.map(m=>`<div class="profile" data-profile="${esc(m.id)}"><div class="profile-grid"><label>Name<input data-profile-field="name" value="${esc(m.name)}"></label><label>Likes<input data-profile-field="likes" value="${esc((m.likes||[]).join(', '))}"></label><label>Dislikes<input data-profile-field="dislikes" value="${esc((m.dislikes||[]).join(', '))}"></label><label>Spice<select data-profile-field="spiceTolerance"><option value="none" ${m.spiceTolerance==='none'?'selected':''}>None</option><option value="mild" ${m.spiceTolerance==='mild'?'selected':''}>Mild</option><option value="normal" ${m.spiceTolerance==='normal'?'selected':''}>Normal</option></select></label></div><label>Notes<input data-profile-field="notes" value="${esc(m.notes||'')}"></label></div>`).join('')}
function renderFeedback(){const p=approved();if(!p){$('feedbackMeals').innerHTML='<p class="hint">Approve a week first.</p>';return}const members=state.familyMembers.filter(m=>m.role!=='helper');$('feedbackMeals').innerHTML=p.days.flatMap(d=>['lunch','dinner'].map(k=>({day:d.day,dish:d[k]}))).map((x,i)=>`<div class="inventory-row"><div><b>${esc(x.dish.name)}</b><div class="shop-source">${esc(x.day)}</div><select id="rm-${i}"><option value="">Whole family</option>${members.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('')}</select><div class="rating-buttons">${[['loved','😍 Loved'],['again','👍 Again'],['okay','😐 Okay'],['avoid','👎 Avoid']].map(([r,l])=>`<button data-rate-dish="${esc(x.dish.name)}" data-rate="${r}" data-member="rm-${i}">${l}</button>`).join('')}</div></div></div>`).join('')}
function renderSignals(){const f=buildFeedbackContext(state),low=state.inventory.filter(x=>x.status!=='plenty').length,top=state.topUpRequests.filter(x=>!x.resolved).length;$('planningSignals').innerHTML=`<div class="summary"><b>${state.ui.chineseExposureTarget||3}/5</b><span>Chinese target</span></div><div class="summary"><b>${f.recentDishes.length}</b><span>recent dishes</span></div><div class="summary"><b>${low}</b><span>items low/out</span></div><div class="summary"><b>${top}</b><span>top-ups</span></div>`}
function renderRequests(){const w=$('weekStart').value;$('requestList').innerHTML=state.mealRequests.filter(r=>!r.weekId||r.weekId===w).map(r=>`<span class="chip">${esc(r.text)} <button class="tiny" data-remove-request="${esc(r.id)}">×</button></span>`).join('')||'<span class="hint">No requests yet.</span>'}
function render(){if(!$('weekStart').value)$('weekStart').value=nextMonday();$('chineseTarget').value=String(state.ui.chineseExposureTarget||3);$('weekBadge').textContent=$('weekStart').value;renderRequests();renderSignals();renderPlan();renderInventory();renderShopping();renderFeedback();renderFamily();mode(state.ui.mode||'parent');tab(state.ui.activeTab||'plan');renderCloud()}

$('parentModeBtn').onclick=()=>mode('parent');$('helperModeBtn').onclick=()=>mode('helper');document.querySelectorAll('#parentTabs button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
$('chineseTarget').onchange=()=>{const n=clone(state);n.ui.chineseExposureTarget=Number($('chineseTarget').value);persist(n)};
$('addRequestBtn').onclick=()=>{const t=$('mealRequestText').value.trim();if(!t)return;const n=clone(state);n.mealRequests.push({id:`req-${Date.now()}`,text:t,weekId:$('weekStart').value});$('mealRequestText').value='';persist(n)};
$('requestList').onclick=e=>{const id=e.target.dataset.removeRequest;if(id){const n=clone(state);n.mealRequests=n.mealRequests.filter(r=>r.id!==id);persist(n)}};
$('generateBtn').onclick=async()=>{const key=$('apiKey').value.trim();if(!key)return note('Enter Anthropic API key.',true);const b=$('generateBtn');b.disabled=true;b.textContent='Generating…';try{const w=$('weekStart').value,p=buildWeeklyPrompt(state,w),raw=await callAnthropic(key,p.system,p.user,5000),candidate={...raw,id:raw.id||`plan-${w}-${Date.now()}`,weekStart:w,status:'draft'};const v=validateWeeklyPlan(candidate);if(!v.ok)throw new Error(v.errors.join('; '));const n=clone(state);n.weeklyPlans=n.weeklyPlans.filter(x=>!(x.status==='draft'&&x.weekStart===w));n.weeklyPlans.push(candidate);persist(n);note('Draft generated.')}catch(e){note(e.message,true)}finally{b.disabled=false;b.textContent='Generate draft week'}};
$('weeklyPlan').onclick=async e=>{const day=e.target.dataset.swapDay,slot=e.target.dataset.swapSlot,p=draft(),key=$('apiKey').value.trim();if(!day||!slot||!p||!key)return;try{const q=buildSwapPrompt(state,p.id,day,slot),dish=await callAnthropic(key,q.system,q.user,1800),next=applySwap(p,day,slot,dish),n=clone(state),i=n.weeklyPlans.findIndex(x=>x.id===p.id);n.weeklyPlans[i]=next;persist(n);note(`${day} ${slot} swapped.`)}catch(err){note(err.message,true)}};
$('approveBtn').onclick=()=>{const p=draft();if(!p)return;const n=clone(state);n.weeklyPlans=n.weeklyPlans.map(x=>x.status==='approved'?{...x,status:'completed'}:x);const i=n.weeklyPlans.findIndex(x=>x.id===p.id);n.weeklyPlans[i]={...n.weeklyPlans[i],status:'approved',approvedAt:new Date().toISOString()};n.shoppingItems=buildShoppingList({ingredients:allIngredients(n.weeklyPlans[i]),inventory:n.inventory,topUps:n.topUpRequests,existing:n.shoppingItems});persist(n);note('Week approved.')};
$('inventorySaveBtn').onclick=()=>{const name=$('inventoryName').value.trim();if(!name)return;persist(upsertInventoryItem(state,{name,domain:$('inventoryDomain').value,status:$('inventoryStatus').value,quantity:$('inventoryQty').value===''?undefined:Number($('inventoryQty').value)},'parent'));$('inventoryName').value='';$('inventoryQty').value=''};
$('inventoryLists').onclick=e=>{if(e.target.dataset.invId)persist(setInventoryStatus(state,e.target.dataset.invId,e.target.dataset.status,'parent'))};$('parentInbox').onclick=e=>{if(e.target.dataset.resolveNote)persist(resolveHouseholdNote(state,e.target.dataset.resolveNote))};
$('shoppingList').onchange=e=>{if(e.target.dataset.shopRoute)persist({...state,shoppingItems:setShoppingRoute(state.shoppingItems,e.target.dataset.shopRoute,e.target.value)});if(e.target.dataset.shopCheck)persist({...state,shoppingItems:setShoppingChecked(state.shoppingItems,e.target.dataset.shopCheck,e.target.checked)})};
$('feedbackMeals').onclick=e=>{if(!e.target.dataset.rateDish)return;persist(recordMealRating(state,{dishName:e.target.dataset.rateDish,rating:e.target.dataset.rate,familyMemberId:$(e.target.dataset.member)?.value||null}));note('Rating saved.')};
$('familyProfiles').onchange=e=>{const f=e.target.dataset.profileField,id=e.target.closest('[data-profile]')?.dataset.profile;if(!f||!id)return;const n=clone(state),m=n.familyMembers.find(x=>x.id===id);m[f]=['likes','dislikes'].includes(f)?e.target.value.split(',').map(x=>x.trim()).filter(Boolean):e.target.value;persist(n)};

function renderHelper(){const v=helperVisibleState(state),low=v.inventory.filter(x=>x.status!=='plenty').length,buys=v.shoppingItems.filter(x=>x.route==='helper_buys'&&!x.checked).length;$('helperDashboard').innerHTML=`<article class="card"><h2>Household status</h2><div class="summary-grid"><div class="summary"><b>${low}</b><span>low/out</span></div><div class="summary"><b>${buys}</b><span>to buy</span></div></div></article><article class="card"><h2>This week's meals</h2>${v.approvedPlan?`<b>Week ${esc(v.approvedPlan.weekStart)}</b>`:'<p class="hint">No approved plan.</p>'}</article>`;$('helperStock').innerHTML=`<article class="card"><h2>Current stock</h2>${v.inventory.map(i=>`<div class="inventory-row"><b>${esc(i.name)}</b><div class="status-buttons">${['plenty','low','out'].map(s=>`<button data-helper-inv="${esc(i.id)}" data-helper-status="${s}" class="${i.status===s?'active':''}">${s}</button>`).join('')}</div></div>`).join('')||'No stock yet.'}</article>`;$('helperShopping').innerHTML=v.shoppingItems.map(i=>`<div class="shopping-row ${i.checked?'checked':''}"><input type="checkbox" data-helper-shop="${esc(i.id)}" ${i.checked?'checked':''}><div><b>${esc(i.name)}</b><div class="shop-source">${esc(i.route)}</div></div></div>`).join('')||'No shopping list.';const p=v.approvedPlan;$('helperMeals').innerHTML=p?`<article class="card"><h2>Approved meals</h2>${p.days.map(d=>`<div class="inventory-row"><div><b>${esc(d.day)}</b><div class="meal-desc">Lunch: ${esc(d.lunch.name)}<br>Dinner: ${esc(d.dinner.name)}</div></div></div>`).join('')}</article><article class="card"><h2>Prep</h2>${(p.helperPrep||[]).map(x=>`<p>• ${esc(x)}</p>`).join('')}</article>`:'<article class="card">No approved plan.</article>';$('helperInbox').innerHTML=v.householdNotes.map(n=>`<div class="inbox-row">${esc(n.text)}</div>`).join('')||'No notes.'}
document.querySelectorAll('#helperTabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#helperTabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.helper-panel').forEach(x=>x.classList.toggle('hidden',x.id!==`htab-${b.dataset.htab}`))});
$('helperTopUpBtn').onclick=()=>{const name=$('helperTopUpName').value.trim();if(!name)return;let n=addTopUpRequest(state,name,$('helperTopUpDomain').value,$('helperTopUpRoute').value,'helper');n.shoppingItems=buildShoppingList({ingredients:allIngredients(approved()),inventory:n.inventory,topUps:n.topUpRequests,existing:n.shoppingItems});$('helperTopUpName').value='';persist(n)};
$('helperStock').onclick=e=>{if(e.target.dataset.helperInv)persist(setInventoryStatus(state,e.target.dataset.helperInv,e.target.dataset.helperStatus,'helper'))};$('helperShopping').onchange=e=>{const id=e.target.dataset.helperShop;if(!id)return;let n={...state,shoppingItems:setShoppingChecked(state.shoppingItems,id,e.target.checked)},item=state.shoppingItems.find(x=>x.id===id);if(e.target.checked&&item?.source==='helper_topup')n=resolveTopUpByName(n,item.name);persist(n)};$('helperNoteBtn').onclick=()=>{const t=$('helperNoteText').value.trim();if(t){$('helperNoteText').value='';persist(addHouseholdNote(state,t,'helper'))}};

function partyCourse(label,d){if(!d?.name)return '';return `<div class="course-card"><div class="shop-source">${esc(label)}</div><h3>${esc(d.name)}</h3><div class="meal-desc">${esc(d.description||'')}</div></div>`}
$('partyGenerateBtn').onclick=async()=>{const key=$('partyApiKey').value.trim()||$('apiKey').value.trim();if(!key)return note('Enter Anthropic API key.',true);try{const p=buildPartyPrompt({guests:Number($('partyGuests').value||8),cuisine:$('partyCuisine').value,dietary:$('partyDietary').value.trim(),notes:$('partyNotes').value.trim(),date:$('partyDate').value}),r=await callAnthropic(key,p.system,p.user,5000),m=r.menu||{};$('partyResults').innerHTML=`<article class="card"><h2>${esc(r.partyTitle||'Dinner Party')}</h2>${[['Welcome',m.welcome],['Starter',m.starter],['Soup',m.soup],...(m.mains||[]).map(x=>['Main',x]),...(m.sides||[]).map(x=>['Side',x]),['Dessert',m.dessert]].map(([l,d])=>partyCourse(l,d)).join('')}<h2>Helper</h2><p>${esc(r.helperInstructions||'')}</p></article>`}catch(e){note(e.message,true)}};

async function hydrate(){cloudProfile=await loadProfile(cloudClient);if(!cloudProfile)return;state=migrateState(mergeCloudState(state,await loadHouseholdState(cloudClient,cloudProfile.household_id)));state.ui.mode=cloudProfile.role==='helper'?'helper':'parent';saveState(localStorage,state);render()}
function renderCloud(){const enabled=cloudEnabled(cfg);$('loginControls').classList.toggle('hidden',!enabled||!!cloudProfile);$('logoutBtn').classList.toggle('hidden',!cloudProfile);$('cloudStatus').textContent=cloudProfile?`Signed in · ${cloudProfile.display_name||cloudProfile.user.email}`:enabled?'Shared household login':'Local mode';$('cloudDetail').textContent=cloudProfile?`${cloudProfile.role} · household sync active`:enabled?'Sign in to sync across devices.':'This browser stores household data locally.';$('parentModeBtn').disabled=!!cloudProfile;$('helperModeBtn').disabled=!!cloudProfile}
$('loginBtn').onclick=async()=>{try{await signIn(cloudClient,$('loginEmail').value.trim(),$('loginPassword').value);await hydrate();note('Signed in.')}catch(e){note(e.message,true)}};$('logoutBtn').onclick=async()=>{await signOut(cloudClient);cloudProfile=null;state=loadState(localStorage);render()};
async function initCloud(){if(!cloudEnabled(cfg))return renderCloud();try{cloudClient=await createSupabase(cfg);const {data:{session}}=await cloudClient.auth.getSession();if(session)await hydrate();renderCloud()}catch(e){note(`Cloud init failed: ${e.message}`,true)}}
render();initCloud();